package com.city.online.api.model;

import com.city.online.api.model.base.MongoAuditBaseEntity;
import com.city.online.api.model.enums.ProductType;
import com.city.online.api.model.enums.Status;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.persistence.Id;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

@Data
@NoArgsConstructor
@Document(collection = "productInventory")
public class Product extends MongoAuditBaseEntity implements Serializable {
    //This field is equivalentTo foodItemId which is unique and generated by using UUID
    @Id
    String id;
    String cuisineType;
    private String itemName;
    private String description;
    private Integer itemPrice;
    ProductType productType;
    boolean veg;
    Integer inventoryCount;
    //SAved in the cart
    Integer cartCount;
    Integer cartPriceTotal;
    //Saved in the user order table
    Integer orderedCount;
    private List<String> foodImageUrls;
    //It will be the restaurantUser OR Ecommerce vendor
    private String vendorId;
    private String username;
    Status status = Status.UNDER_REVIEW;
}
